Drugs = new Mongo.Collection('drugs');

drugs= [
"Acetazolamide Injection 500 mg",
"Acetazolamide Tablet 250 mg",
"Acetylcysteine Injection 200 mg/mL",
"Acetylsalicylic Acid Tablet 300 mg",
"Acetylsalicylic Acid Tablet 75 mg (Dispersible)",
"Activated Charcoal Powder 50 g",
"Acyclovir Cream 5%",
"Acyclovir Eye Ointment 3%",
"Acyclovir Injection 250 mg vial",
"Acyclovir Suspension 200 mg/5 mL",
"Acyclovir Tablet, 200 mg",
"Adrenaline Injection, 1 mg/1mL (1:1000)",
"Adrenaline Injection, 1:10,000",
"Adriamycin Injection, 50 mg",
"Albendazole Syrup, 100 mg/5 mL",
"Albendazole Tablet, 200 mg",
"Albendazole Tablet, 400 mg",
"Allopurinol Tablet, 100 mg",
"Allopurinol Tablet, 300 mg",
"Aluminium Hydroxide Mixture",
"Amino Acid Solution Injection, 10%",
"Amino Acid Solution Injection, 20%",
"Aminophylline Injection, 250 mg/10 mL",
"Amiodarone Tablet, 200 mg",
"Amitriptyline Tablet, 10 mg",
"Amitriptyline Tablet, 25 mg",
"Amitriptyline Tablet, 50 mg",
"Amlodipine Tablet, 5 mg",
"Amlodipine Tablet, 10 mg",
"Amodiaquine + Artesunate Granular Powder, 75 mg + 25 mg",
"Amodiaquine + Artesunate Granular Powder, 150 mg + 50 mg",
"Amodiaquine + Artesunate Tablet, 75 mg + 25 mg (6 tabs)",
"Amodiaquine + Artesunate Tablet, 150 mg + 50 mg (12 tabs)",
"Amoxicillin + Clavulanic Acid Injection, 500 mg + 100 mg",
"Amoxicillin + Clavulanic Acid Injection, 1.2g",
"Amoxicillin + Clavulanic Acid Suspension, 250 mg + 62 mg",
"Amoxicillin + Clavulanic Acid Suspension, 400 mg + 57 mg",
"Amoxicillin + Clavulanic Acid Tablet, 500 mg + 125 mg",
"Amoxicillin + Clavulanic Acid Tablet, 875 mg + 125 mg",
"Amoxicillin Capsule, 250 mg",
"Amoxicillin Capsule, 500 mg",
"Amoxicillin Suspension, 125 mg/5 mL",
"Ampicillin Injection, 500 mg",
"Artemether + Lumefantrine Tablet, 40 mg + 240 mg (12’s)",
"Artemether + Lumefantrine Tablet, 80 mg + 480 mg (6’s)",
"Artemether Injection, 40 mg/mL",
"Artemether Injection, 80 mg/mL",
"Artesunate Injection, 60mg",
"Artesunate Suppository, 50 mg",
"Artesunate Suppository, 200 mg",
"Atenolol + Hydrochlorthiazide Tablet, 50 mg + 25 mg",
"Atenolol + Hydrochlorthiazide Tablet, 100 mg + 25 mg",
"Atenolol Injection, 500 microgram/10 mL",
"Atenolol Tablet, 25 mg",
"Atenolol Tablet, 50 mg",
"Atenolol Tablet, 100 mg",
"Atorvastatin Tablet, 10 mg",
"Atorvastatin Tablet, 20 mg",
"Atropine Eye Drops, 1%",
"Atropine Injection, 0.6 mg/mL",
"Azithromycin Capsule, 250 mg",
"Azithromycin Oral Suspension, 200 mg/5 mL",
"Azithromycin Oral Suspension, 200 mg/5 mL",
]